### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by noySq** [Pesekjak/Hippo#4]
Skript 2.7 seems to broke this addon. Will there be any updates?

**Comment by ToxykAuBleu** [comment]
With a little more investigation, you're right. I accidently submit a issue on Skript-reflect's page due to a strange behavior. So here it is, please see https://github.com/TPGamesNL/skript-reflect/issues/76#issue-1931869539
(I send this message because I saw on my severe error this line: 
at ippo.jar//me.pesekjak.hippo.skript.Types$7.parse(Types.java:357))

**Comment by Pesekjak** [comment]
Yes, I know it does not work and I am working on a new version for 2.7 but I can't say for sure when it will be ready.
